// ============================================
// File Model - Mongoose Schema
// ============================================
// This schema defines the structure for storing
// file/image metadata in MongoDB.
// Each uploaded file gets an entry with its
// original name, stored name, path, URL, MIME type,
// size, and upload timestamp.
// ============================================

const mongoose = require("mongoose");

const fileSchema = new mongoose.Schema(
  {
    // The original name of the file as uploaded by the user
    // e.g., "my-profile-photo.jpg"
    originalName: {
      type: String,
      required: [true, "Original file name is required"],
    },

    // The unique name generated by the server to avoid conflicts
    // e.g., "1716849600000-my-profile-photo.jpg"
    fileName: {
      type: String,
      required: [true, "File name is required"],
      unique: true,
    },

    // The relative path where the file is stored on disk
    // e.g., "uploads/1716849600000-my-profile-photo.jpg"
    filePath: {
      type: String,
      required: [true, "File path is required"],
    },

    // The full URL to access/download the file via the API
    // e.g., "http://localhost:5000/uploads/1716849600000-my-profile-photo.jpg"
    fileUrl: {
      type: String,
      required: [true, "File URL is required"],
    },

    // The MIME type of the file for validation and serving
    // e.g., "image/jpeg", "image/png"
    fileType: {
      type: String,
      required: [true, "File type is required"],
    },

    // The size of the file in bytes
    // Used for displaying file info and enforcing limits
    fileSize: {
      type: Number,
      required: [true, "File size is required"],
    },

    // Timestamp of when the file was uploaded
    // Defaults to the current date/time
    uploadedAt: {
      type: Date,
      default: Date.now,
    },
  },
  {
    // Mongoose adds createdAt and updatedAt fields automatically
    timestamps: true,
  }
);

// Export the model so it can be used in controllers
module.exports = mongoose.model("File", fileSchema);
